In [1]:
import numpy as np

### Problem 1

In [2]:
A = np.array([[5,4,3,2,1], [-1,1,0,1,-1]], dtype='float64')

#### 1. Center each row by sbutracting the mean from each measurements

In [3]:
def center_data(A):
    m = np.mean(A, axis=1, keepdims=True)
    A -= m
    return A

A = center_data(A)

print(A)

[[ 2.  1.  0. -1. -2.]
 [-1.  1.  0.  1. -1.]]


#### 2. Use SVD to find the combinations of data that contains the most information

In [4]:
def PCA(A):
    S = A.dot(A.T) / (A.shape[1] - 1)
    return np.linalg.eig(S)

eigenvalues, eigenvectors = PCA(A)
print(eigenvalues)
print(eigenvectors)

[ 2.5  1. ]
[[ 1.  0.]
 [ 0.  1.]]


### Problem 2

In [5]:
A = np.array([[1,0,1,0,1,0], [1,2,3,3,2,1]], dtype='float64')

In [6]:
A = center_data(A)
print(A)

[[ 0.5 -0.5  0.5 -0.5  0.5 -0.5]
 [-1.   0.   1.   1.   0.  -1. ]]


In [7]:
eigenvalues, eigenvectors = PCA(A)
print(eigenvalues)
print(eigenvectors)

[ 0.3  0.8]
[[ 1.  0.]
 [ 0.  1.]]


### Problem 3

In [8]:
A = np.array([[1,2,3], [5,2,2]], dtype='float64')

In [9]:
A = center_data(A)
print(A)

[[-1.  0.  1.]
 [ 2. -1. -1.]]


In [10]:
S = A.dot(A.T) / (A.shape[1] - 1)
print(S)
print("Variance S1^2 =", S[0,0], ", S2^2 =", S[1,1])
eigenvalues, eigenvectors = PCA(A)
print(eigenvalues)

[[ 1.  -1.5]
 [-1.5  3. ]]
Variance S1^2 = 1.0 , S2^2 = 3.0
[ 0.19722436  3.80277564]


### Problem 4

In [11]:
A = np.array([[1,-1, 0, 0], [0,0,2,-2], [1,1,-1,-1]], dtype='float64')
A = center_data(A)
S = A.dot(A.T) / (A.shape[1] - 1)
print(S)
eigenvalues, eigenvectors = PCA(A)
print(eigenvalues)
print(eigenvectors)

[[ 0.66666667  0.          0.        ]
 [ 0.          2.66666667  0.        ]
 [ 0.          0.          1.33333333]]
[ 0.66666667  2.66666667  1.33333333]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
